-------------------------------------------------------------------------------
There are messages associated with the following module(s):
-------------------------------------------------------------------------------

Anaconda3/2022.10:
   We recommend that you use the following 2022 (sub)version of Anaconda3 -
   "Anaconda3/2022.05". The latest module, Anaconda3/2022.10, is under
   investigation as this has demonstrated odd behaviour on conda environment
   exit (for some users). We will investigate this, and advise in due
   course.

-------------------------------------------------------------------------------

  0%|          | 0/1033 [00:00<?, ?it/s]  0%|          | 0/1033 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "llama_replicate.py", line 90, in <module>
    predictions_all_prompts = run_predictions(df.Idiom, df.Sentence, args.model_abr, args.setting)
  File "llama_replicate.py", line 75, in run_predictions
    raw_output_p1 = prompt_model(raw_prompt1)
  File "llama_replicate.py", line 23, in prompt_model
    output = replicate.run(
  File "/mnt/parscratch/users/acq22zm/anaconda/.envs/semeval-t4/lib/python3.8/site-packages/replicate/client.py", line 174, in run
    return run(self, ref, input, use_file_output, **params)
  File "/mnt/parscratch/users/acq22zm/anaconda/.envs/semeval-t4/lib/python3.8/site-packages/replicate/run.py", line 46, in run
    prediction = client.models.predictions.create(
  File "/mnt/parscratch/users/acq22zm/anaconda/.envs/semeval-t4/lib/python3.8/site-packages/replicate/model.py", line 405, in create
    resp = self._client._request(
  File "/mnt/parscratch/users/acq22zm/anaconda/.envs/semeval-t4/lib/python3.8/site-packages/replicate/client.py", line 89, in _request
    _raise_for_status(resp)
  File "/mnt/parscratch/users/acq22zm/anaconda/.envs/semeval-t4/lib/python3.8/site-packages/replicate/client.py", line 385, in _raise_for_status
    raise ReplicateError.from_response(resp)
replicate.exceptions.ReplicateError: ReplicateError Details:
title: Free time limit reached
status: 402
detail: You have reached the free time limit. To continue using Replicate, set up billing at https://replicate.com/account/billing#billing.
